In [124]:
import nltk
# nltk.download('punkt')
# nltk.download('averaged_perceptron_tagger')
# nltk.download('wordnet')
import re
from nltk import pos_tag
from nltk.tokenize import word_tokenize
from nltk.corpus import wordnet as wn
import pandas as pd

import pandas as pd
import spacy
from spacy.training import Example

In [125]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 1.8 MB/s eta 0:00:00a 0:00:01m

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: pip3.11 install --upgrade pip
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

- en_core_web_sm — это одна из предобученных моделей для обработки естественного языка (NLP), предоставляемая библиотекой spaCy. Эта модель предназначена для работы с английским языком и включает в себя различные функции для анализа текста.

- Функции:

- Токенизация: Разделение текста на отдельные токены (слова, знаки препинания и т.д.).
- Разметка по частям речи (POS tagging): Определение частей речи для каждого токена (существительное, глагол, прилагательное и т.д.).
- Лемматизация: Приведение слов к их начальной форме (например, "running" к "run").
- Синтаксический анализ: Определение грамматической структуры предложения, включая зависимые отношения между словами.
- Распознавание именованных сущностей (NER): Выделение именованных сущностей, таких как имена людей, организации, даты и т.д.

In [126]:
file_path = "/Users/MAC/Desktop/Компьютерная лингвистика/articles.txt"

def split_articles_by_title(file_path):
    with open(file_path, encoding="utf-8") as file:
         content = file.read()
    #разделяем содержимое по вхождениям "Title:" с сохранением этого слова в начале каждого блока
    articles = content.split("\nTitle:")
    
    #очищаем каждую статью от лишних пробелов и символов
    articles = [article.replace('\n', ' ').strip() for article in articles]
    
    return articles

articles = split_articles_by_title(file_path)

#выводим первую статью
print(articles[0])

Title: Combining Machine Learning and Computational Chemistry for Predictive Insights Into Chemical Systems Authors: Bingqing Cheng, Valentin Vassilev-Galindo, John A Keith, Alexandre Tkatchenko, Klaus-Robert Müller, Stefan Chmiela, Michael Gastegger Organizations:  †Department of Chemical and Petroleum Engineering Swanson School of Engineering, University of Pittsburgh, Pittsburgh, Pennsylvania 15261, United States,  ‡Department of Physics and Materials Science, University of Luxembourg, L-1511 Luxembourg City, Luxembourg,  ¶Accelerate Programme for Scientific Discovery, Department of Computer Science and Technology, 15 J. J. Thomson Avenue, Cambridge CB3 0FD, United Kingdom,  §Department of Software Engineering and Theoretical Computer Science, Technische Universität Berlin, 10587, Berlin, Germany,  §Department of Software Engineering and Theoretical Computer Science, Technische Universität Berlin, 10587, Berlin, Germany,  ∥Machine Learning Group, Technische Universität Berlin, 10587, Berlin, Germany Text:  Machine learning models are poised to make a transformative impact on chemical sciences by dramatically accelerating computational algorithms and amplifying insights available from computational chemistry methods. However, achieving this requires a confluence and coaction of expertise in computer science and physical sciences. This Review is written for new and experienced researchers working at the intersection of both fields. We first provide concise tutorials of computational chemistry and machine learning methods, showing how insights involving both can be achieved. We follow with a critical review of noteworthy applications that demonstrate how computational chemistry and machine learning can be used together to provide insightful (and useful) predictions in molecular and materials modeling, retrosyntheses, catalysis, and drug design. A lasting challenge in applied physical and chemical sciences has been to answer the question: how can one identify and make chemical compounds or materials that have optimal properties for a given purpose? A substantial part of research in physics, chemistry, and materials science concerns the discovery and characterization of novel compounds that can benefit society, but most advances still are generally attributed to trial-and-error experimentation, and this requires significant time and cost. Current global challenges create greater urgency for faster, better, and less expensive research and development efforts. Computational chemistry (CompChem) methods have significantly improved over time, and they promise paradigm shifts in how compounds are fundamentally understood and designed for specific applications. Machine learning (ML) methods have in the past decades witnessed an unprecedented technological evolution enabling a plethora of applications, some of which have become daily companions in our lives.1−3 Applications of ML include technological fields, such as web search, translation, natural language processing, self-driving vehicles, control architectures, and in the sciences, for example, medical diagnostics,4−723 particle physics,8 nano sciences,9 bioinformatics,10,11 brain-computer interfaces,12 social media analysis,13 robotics,14,15 and team, social, or board games.16−18 These methods have also become popular for accelerating the discovery and design of new materials, chemicals, and chemical processes.19 At the same time, we have witnessed hype, criticism, and misunderstanding about how ML tools are to be used in chemical research. From this, we see a need for researchers working at the intersection of CompChem+ML to more critically recognize the true strengths and weaknesses of each component in any given study. Specifically, we wanted to review why and how CompChem+ML can provide useful insights into the study of molecules and materials. While developing this Review, we polled the scientific community with an anonymous online survey that asked for questions and concerns regarding the use of ML models with chemistry applications. Respondents raised excellent points including: ML methods are becoming less understood while they are also more regularly used as black box tools. Many publications show inadequate technical expertise in ML (e.g., inappropriate splitting of training, testing, and validation sets). It can be difficult to compare different ML methods and know which is the best for a particular application or whether ML should even be used at all. Data quality and context are often missing from ML modeling, and data sets need to be made freely available and clearly explained. Additionally, when asked about the most exciting active and emerging areas of ML in the next five years, respondents mentioned a wide range of topics from catalysis discovery, drug and peptide design, “above the arrow” reaction predictions, and generative models that promise to fundamentally transform chemical discovery. When asked about challenges that ML will not surmount in the next five years, respondents mentioned modeling complex photochemical and electrochemical environments, discovering exact exchange-correlation functionals, and completely autonomous reaction discovery. This Review will give our perspective on many of these topics. As context for this Review, Figure 1 shows a heatmap depicting the frequency of ML keywords found in scientific articles that also have keywords associated with different American Chemical Society (ACS) technical divisions. Preparing this figure required several steps. First, lists of ML keywords were chosen. Second, lists of keywords were created by perusing ACS division symposia titles from over the past five years. Third, Python scripts used Scopus Application Programming Interfaces (APIs) to identify the number of scientific publications that matched sets of ML and division symposia keywords. Figure 1 elucidates several interesting points. First, the most popular ML approaches across all divisions are clearly neural networks, followed by genetic algorithms and support vector machines/kernel methods. Second, divisions such as physical (PHYS), analytical (ANYL), and environmental (ENVR) are already using diverse sets of ML approaches, while divisions such as inorganic (INOR), nuclear (NUCL), and carbohydrate (CARB) are primarily employing more distinct subsets of approaches, while other divisions, such as educational (CHED), history (HIST), law (CHAL), and business-oriented divisions (BMGT and SCHB), that is, divisions that produce much fewer scholarly journal articles, are not linking to publications that mention ML. Third, ML has had more prevalence across practically all divisions over time. For further insight, Table 1 lists the top four keywords obtained from recent ACS symposium titles, as well as their respective contribution percentage reflected in Figure 1. There, one sees that a handful of keywords can significantly overshadow matches in some of the bins, for exampled, “electro”, “sensor”, “protein”, and “plastic”. With any ML application, there will be a risk of imperfect data or user bias, but this is a useful launch point to appreciate how and where ML is being used in chemical sciences. A key takeaway is that we are witnessing an unprecedented crescendo in interest in ML over the last ten years (e.g., Figure 1c) thanks to improved understanding of the intersectionality of traditional science and engineering disciplines with rapidly evolving disciplines such as CompChem and data science.  Heatmaps illustrating the extent that ML terms appear in scientific papers aligned by American Chemical Society (ACS) technical divisions from 2000 to 2010 (a) and from 2010–present (b). (c) Line graph showing the number of occurrences of any ML term being found in papers attributed to the ACS PHYS division, from 2000–present. Figures were made by Charles D. Griego. Python scripts used to generate these figures and corresponding Table 1 are freely available with a creative commons attribution license. Readers are welcome to use, adapt, and share these scripts with appropriate attribution: https://github.com/keithgroup/scopus_searching_ML_in_chem_literature.). The survey results and literature analysis above showed an opportunity for a tutorial reference to help readers address future research challenges that will require joint applications of CompChem, ML, and chemical and physical intuition (CPI). This review will classify concepts using a rendition of a “data to wisdom” hierarchy, Figure 2. Scholars have noted shortcomings with similar constructs,20 but we use it to reflect a stepladder for scientific progress, starting from collecting data and ending with overall impact. CompChem, ML, and CPI each have different strengths and weaknesses and bring synergistic opportunities. CPI alone can be employed to climb the ladder from data to impact, but current CPI may only provide limited understanding or applicability outside of available data sets. However, CompChem is extraordinarily well-suited for generating high quality data that contain useful information (vide infra, section 2) often more easily than via traditional experimentation. ML is likewise extremely well-suited for recognizing and accurately quantifying nonlinear relationships (vide infra, section 3), a task that is especially difficult for even the most expert-level CPI alone. A key opportunity is that useful ML requires robust data sets, and these can be provided by CompChem as long as the CPI component is selecting and correctly interpreting appropriate methods for the task at hand to productively climb the ladder toward impact (vide infra, section 4). We stress that the impact generation process shown in Figure 2 is by no means a linear one — on the contrary, it contains many loops and dead ends. As we show later (in Section 4), within the troika of CompChem+ML+CPI, ML acts as a catalyst that accelerates explorative data-driven hypotheses generation. Automatically generated hypotheses are then validated and calibrated with CompChem and CPI to yield further improved ML modeling (enriched by more physical prior knowledge), which then loops back with improved hypotheses. This feedback loop is the key to the modern knowledge discovery leading to insight, wisdom and hopefully positive impacts to society.  Data–knowledge–wisdom hierarchy stepladder. We consider quantum mechanics as described by the nonrelativistic time-independent Schrödinger equation as our “standard model” because it accurately represents the physics of charged particles (electrons and nuclei) that make up almost all molecules and materials. Indeed, this opinion has been held by some for almost a century: The fundamental laws necessary for the mathematical treatment of a large part of physics and the whole of chemistry are thus completely known, and the difficulty lies only in the fact that application of these laws leads to equations that are too complex to be solved. P. A. M. Dirac, 1929 Any theoretical method for predicting molecular or material phenomena must first be rooted in quantum mechanics theory and then suitably coarse-grained and approximated so that it can be applied in a practical setting. CompChem, or more precisely, computational quantum chemistry defines computationally driven numerical analyses based on quantum mechanics. In this section, we will explain how and why different CompChem methods capture different aspects of underlying physics. Specifically, this section provides a concise overview of the broad range of CompChem methods that are available for generating data sets that would be useful for ML-assisted studies of molecules and materials. Models extract information from data. The renowned statistician George Box famously discussed “good models” as those characterized as “simple”, “illuminating”, and “useful”.21 Good models should be parsimonious and describe essential relationships without overelaboration. The ideal gas equation, PV = nRT, exemplifies a good model. The ideal gas equation relates macroscopic pressure (P), volume (V), number of molecules (n), and temperature (T) of gases under idealized conditions, without requiring explicit knowledge of the processes occurring on an atomic scale. Its simple functional form needs just one parameter, the ideal gas constant R, and this makes it possible to formulate useful insights, such as how at constant pressure a gas expands with rising temperature. On the other hand, this elegant equation only holds for conditions where the gas behaves as an ideal gas. The derivation of more accurate models of gases requires more mathematically complicated equations of state that rely on more free parameters22 that in turn obfuscate physical insights, require more computational effort to solve, and thus make the model less “good”. This example also offers a convenient connection to ML models that will be discussed later in section 3. As mathematical models for complex phenomena become more complicated and less intuitive to derive, ML models that infer nonlinear relationships from data become more applicable when increasing amounts of empirical data become available. Alternatively, the conventional CompChem treatment entails first determining the system’s relevant geometry and its total ground state energy, and from that physical properties of interest (e.g., pressure, volume, band gap, polarizability, etc.) can be obtained using quantum and statistical mechanics. In this section, we discuss the relevant CompChem methods for these. While the mathematical physics for these methods might occasionally be too complicated for a user to fully understand, many algorithms exist so that they can still be easily run in a “black-box” way with modern computational chemistry software and accompanying tutorials.23−26 CompChem thus serves as an invaluable tool to generate data and information for knowledge and insights across many length and time scales. Figure 3 is an adaption of a multiscale hierarchy of different classes of CompChem methods. It shows their applicability for modeling different length and time scales and depicts how large scale models may be developed based on smaller scale theories.  Hierarchy of computational methods and corresponding time and length scales. QM stands for Quantum Mechanics. Integral to every CompChem study is the user’s representation for the system, that is, how the user chooses to describe the system. CompChem representations can range from simple and lucid (e.g., a precise chemical system such as a water molecule isolated in a vacuum) to complex and ambiguous (e.g., a putative but speculative depiction of a solid–liquid interface under electrochemical conditions). Approximate wavefunctions (expressed on a basis set of mathematical functions) or approximate Hamiltonians (referred to as levels of theory) as described below in this section can also be considered representations. One might then say that many representations for different components of a system will constitute an overall representation, and this is true. The point we make is that the validity of any computational result depends on the overall representation, and sometimes an incorrect representation may provide a correct result due to “fortuitous error cancellation”. In CompChem studies, a valid representation is one that captures the nature of the physical phenomena of a system. For a molecular example, if one is determining the bond energy of a large biodiesel molecule using CompChem methods,27 it may or may not be justified to approximate a nearby long-chain alkyl group (−CnH(2n+1)) simply as a methyl (−CH3) or even a hydrogen atom. Indeed, choosing such a representation can sometimes be a useful example of CPI since alkyl bonds usually exhibit relatively short-ranged interactions (a feature that will be discussed in the context of ML in more detail in section 4.1.3.). An atomic scale geometry with fewer atoms would reduce the computational cost of the study or allow a more accurate but more computationally expensive calculation to be run. On the other hand, it might also be a poor choice if the chemical group, for example, a substituted alkyl group participated in physical organic interactions, such as subtle steric, induction, or resonance effects.28 For a solid-state example, a user might exercise good CPI by assuming that a relatively small unit cell under periodic boundary conditions would capture salient features of a bulk material or a material surface (as is often the case for many metals). On the other hand, subtle symmetry-breaking effects in materials (e.g., distortions arising from tilting octahedra groups in perovskites,29 or surface reconstruction phenomena that occur on single crystals)30 might only be observed when considering larger and more computationally expensive unit cells. Relevant to both examples, it may also be that the CompChem method itself brings errors that obfuscate phenomena that the user intends to model. In general, CompChem errors may be due to 1) errors introduced by the user in the initial set up of the CompChem application, or 2) errors in the CompChem method when treating the physics of the system. In section 3, we will discuss how the choice of ML representation also plays similarly critical roles in determining whether and to what extent an ML model is useful. The quantitative accuracy of a CompChem model stems from its suitability in describing the system. As explained above, an observed accuracy will depend on the representation being used. High-quality CompChem calculations have traditionally been benchmarked against data sets that consist of well-controlled and relatively precise thermochemistry experiments on small, isolated molecules.31,32 The error bars for standard calorimetry experiments are approximately 4 kJ/mol (or 1 kcal/mol or 0.04 eV), and computational methods that can provide greater accuracy than this are stated as achieving “chemical accuracy”. Note that this term should be used when describing the accuracy of the method compared to the most accurate data possible; for example, if one CompChem method was found to reproduce another CompChem method within 1 kJ/mol, but both methods reproduce experimental data with errors of 20 kJ/mol, then neither method should be called chemically accurate. There are many well-established reasons why CompChem models can bring errors. For example, errors may be due to size consistency33 or size extensivity34 problems that are intrinsic within the CompChem method, larger systems sometimes embody significant medium and long-range interactions (e.g., van der Waals forces)35 or self-interaction errors36 that might not be noticeable in small test cases. The recommended path forward is to consider which fundamental interactions are in play in the system and then use a CompChem model that is adequate at describing those interactions. Besides this, users should make use of existing tutorial references that provide practical knowledge about which parameters in a CompChem calculation should be carefully noted, for example ref (37). Historically the most popular CompChem methods for molecular and materials modeling (the B3LYP38 and PBE39 exchange correlation functionals, see section 2.2.3.) are often said to have an expected accuracy of about 10–15 kJ/mol (or 2–4 kcal/mol or 0.1–0.2 eV) when modeling differences between the total energies of two similar systems, and errors are expected to be somewhat larger when considering transition state energies. Though this is used as a simple rule, it is obviously an oversimplification and actual accuracy is only assessed by thoughtful benchmarking of the case being considered.40−44 In CompChem, one normally assumes that any two users using the same representation for the system with the same code on the same computing architecture will obtain the exact same result within the numerical precision of the computers being used. This is not always the cas

In [127]:
#загружаем языковую модель.
nlp = spacy.load("en_core_web_sm")

In [130]:
#скачаем датасет для дообучения модели для распознавания сущностей
file_path = "/Users/MAC/Desktop/Компьютерная лингвистика/NER dataset.csv"
data = pd.read_csv(file_path, encoding='windows-1251')
data

          Sentence #           Word  POS Tag
0        Sentence: 1      Thousands  NNS   O
1                NaN             of   IN   O
2                NaN  demonstrators  NNS   O
3                NaN           have  VBP   O
4                NaN        marched  VBN   O
...              ...            ...  ...  ..
1048570          NaN           they  PRP   O
1048571          NaN      responded  VBD   O
1048572          NaN             to   TO   O
1048573          NaN            the   DT   O
1048574          NaN         attack   NN   O

[1048575 rows x 4 columns]

In [133]:
data[data['Sentence #']== 'Sentence: 1']

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

    Sentence #       Word  POS Tag
0  Sentence: 1  Thousands  NNS   O

O: Это метка "Outside", которая указывает, что токен (слово) не является частью какой-либо именованной сущности. То есть, это слово не относится ни к одной из категорий


B-: Это префикс, который указывает на начало именованной сущности. Например:

B-geo: Начало географической сущности (например, название города или страны).
B-tim: Начало временной сущности (например, дата или время).
B-org: Начало организационной сущности (например, название компании или учреждения).
B-per: Начало персональной сущности (например, имя человека).
B-gpe: Начало геополитической сущности (например, название региона или страны).
B-art: Начало артефактной сущности (например, название произведения искусства).
B-eve: Начало событийной сущности (например, название события).
B-nat: Начало национальной сущности (например, название нации).


I-: Это префикс, который указывает на продолжение именованной сущности. Например:

I-per: Продолжение персональной сущности.
I-org: Продолжение организационной сущности.
I-geo: Продолжение географической сущности.
I-tim: Продолжение временной сущности.
I-gpe: Продолжение геополитической сущности.
I-art: Продолжение артефактной сущности.
I-eve: Продолжение событийной сущности.
I-nat: Продолжение национальной сущности.

##### обучаем модель

In [135]:
#преобразование данных в формат для обучения
train_data = []
current_sentence = []
current_entities = []


for index, row in data.iterrows():
    if pd.isna(row['Word']):
        #если слово пустое, это конец предложения
        if current_sentence: #проверяем, есть ли в current_sentence слова
            train_data.append((current_sentence, {'entities': current_entities}))
            current_sentence = []
            current_entities = []
    else:
        #добавляем слово в текущее предложение
        current_sentence.append(row['Word'])
        if row['Tag'] != 'O':
            #если тег не 'O', добавляем его как сущность
            start = len(' '.join(current_sentence)) - len(row['Word'])
            end = start + len(row['Word'])
            current_entities.append((start, end, row['Tag']))

#обработка последнего предложения, если оно не завершено
if current_sentence:
    train_data.append((current_sentence, {'entities': current_entities}))




# Преобразуем в формат (текст, аннотации)
train_data = [(' '.join(sentence), annotations) for sentence, annotations in train_data]


#обучение модели
for epoch in range(10):  #количество эпох
    for text, annotations in train_data:
        #проверка длины текста
        if len(text) > 200000:
            text = text[:200000]  #обрезаем текст до 200 000 символов для ускорения обучения
        doc = nlp.make_doc(text)#метод make_doc используется для создания объекта doc из строки text. Этот объект представляет собой документ, который будет использоваться для обучения модели. Он содержит токены, которые были созданы из текста. 
        example = Example.from_dict(doc, annotations)
        '''Здесь создается объект example с помощью метода from_dict, который принимает документ doc и аннотации annotations. 
           Этот объект представляет собой пример, который будет использоваться для обновления модели. 
           Он содержит информацию о том, какие токены в документе соответствуют каким сущностям. '''
        nlp.update([example])

#сохранение дообученной модели
nlp.to_disk("my_precious")


#загрузка дообученной модели
nlp_custom = spacy.load("my_precious")


#функция для распознавания сущностей в тексте
def recognize_entities(text):
    doc = nlp_custom(text)
    entities = [(ent.text, ent.label_) for ent in doc.ents]   
    return entities


#функция для фильтрации имен и организаций
def filter_entities(entities):
    filtered = []
    for text, label in entities:
        #проверяем, содержит ли текст число
        if re.search(r'\d', text):
            continue  #пропускаем сущности с числами

        #исключаем сущности с более чем одной заглавной буквой
        if sum(1 for char in text if char.isupper()) > 1:
            continue

        if label in ['B-per', 'I-per']:  #фильтруем только имена и фамилии
            filtered.append((text, label))
    return filtered


#функция для склеивания сущностей и удаления дубликатов
def merge_entities(entities):
    merged_names = set()  #для имен
    for text, label in entities:
        if label in ['B-per', 'I-per']:
            merged_names.add(text)  #добавляем имена и фимилии

    #преобразуем множества обратно в строки
    return {
        'names': ', '.join(merged_names)
    }



#обработка статей
for i, article in enumerate(articles):
    print(f"Статья {i + 1}:")
    entities = recognize_entities(article)
    filtered_entities = filter_entities(entities)
    merged_entities = merge_entities(filtered_entities)



    print("Имена и фамилии:", merged_entities['names'])
    print("\n")

Статья 1:
Имена и фамилии: de, K., minima, symposia, Hyperparameter, Dral, Gastegger, Artrith, Bernstein, ,, Burke, Note, They, Waals, Klucznik, Griego, Atomistic, Θ., Carlo, Kernel, Slater, Investigator, Hermann, Molecules, P., Zhong, Müller, Fermions, Ii, Parinello, A., Gerhard, Exc, Dirac, Ĥel, George, Slater-type, Research, σ(s, Mater, H., kijk, Wu, al, S., Vrep, Stefan, Infrared, F, Computer, Keith, Hilbert, Usually, Ref, i+n, Optimizations, Fock, G., Miller, Professor, Copyright, Lagrange, Wasserstein, T., Bingqing, van, Algorithms, Virtual, von, ref, Chmiela, Al, Brockherde, Alexander, Rappe, Math+, Generally, Parrinello, Screening, Charles, John, Grant, Minima, Koster, N., Raman, A, Hall, Boltzmann, ; Hirzel, Harrison, −, Michael, Alexandre, Ertl, Multiscale, D., Tkatchenko, Bag, Medal, Predictive, −Π, Faculty, Humboldt, Merino, J., Factorization, Monte, kinase, –, Vatt, Fellow, Coulomb, Combining, Box, e.g., Hammett, Review, Efficient, Nature, Lilienfeld, Standard, Zhavoronkov, Coley, R., et, Fédérale, Neural, Recent, Starting, Consolidator, =, Gabriel, Cheng, M., Ci


Статья 2:
Имена и фамилии: Dubé, Ong, Zhang, Overhoff, Mai, Goodswen, Wong, Bao, Zhao, Koslicki, Faris, Lima, Ren, Radakovich, Xu, Kaul, Darko, Vervier, Gregor, Lillicrap, Feng, Wei, and, Staphylococcus, Reel, Peter, A., Campbell, Bezek, Dong, Lee, Hu, B, al, Fu, S., Chadaga, Yu, Schulman, Diaz, Amouzgar, Tang, Yang, Jin, Mazzurana, Delafiori, Ali, Lundberg, Stracy, David, Cammarota, X., Singh, Aila, Laplacian, Chiu, John, Accuracy, Kaufman, Kobak, Yan, Ye, simplex, Tong, Priya, Cobre, Kolli, Dawkins, Rainio, Hopf, Greener, Ma, Oselio, Shan, Liu, Gao, Mirdita, Weis, Lv, Yeung, Kim, Random, Ghosh, Xiang, et, Logistic, =, Mnih, Altman, Mobaderi, Cheng, Li, Chen, Su


Статья 3:
Имена и фамилии: Matthew, K., Evaluating, Carolin, Bias, Johannesson, ligand, Beatson, Mansouri, Outlier, Ŷi, Proxy, Seal, Greene, Cavasotto, Specifically, Naven, Vidler, Sc, Russ, Lavecchia, Sosnin, Dominic, Paisley, Mannhold, James, Bowes, Bio, Manas, Marie, Team, Yi, Badré, Database, Peter, Lab, A., Bioicons, Nigel, R, Screens, Brianna, Rouquie, Sanofi, Cell, Russell, Gonzalez, Nordisk, al, Bjarki, Graph, Greenig, Spjuth, S., Ouedraogo, Dalmas, Curie, Ignota, Shantanu, W., Valbonne, Gaussian, Schapin, David, Secondary, Bracknell, Carpenter, Falgun, Alex, Schwab, Landrum, Due, Novo, Singh, Tautomers, physicochemical, Alexander, Willett, Rhiannon, Pharmacology, Cmax, Worldwide, Bender, Mervin, Spearman, Bradshaw, Senior, Mehrjou, Vice, Manchester, Dr., Adit, Accuracy, Library, Jeremy, Kamel, E, Relay, Raymond, Ola, Overall, Adham, Matt, Pearson, Joshi, Fuzzy, Rapid, Advisor, Kalliokoski, Variance, Michael, Lowe, Lawrence, Patrick, Campus, Excretion, Layla, Parkinson, Shah, Pfizer, J., Lewis, Williams, Adrien, Huang, Ash, Anne, Srijit, Liu, Deidre, Chaitanya, García, al. introduced, Machine, Friederichs, Wilkinson, Box, Vidler writing -, Gao, Enamine, Labs, e.g., Miguel, Arash, Andreas, Weis, Cohen, Principal, Misinterpretations, Quiver, J, Sweden, Caroline, Wilk, Replacement, E., Elsa, Pillars, R., B., Rouquié, et, Cremer, Mechanistic, Paracelsus, Servier, False, Structures, Toxicologist, Schramm, Clevert, =, Brennan


Статья 4:
Имена и фамилии: de, carbapenem, benzylpenicillin, Escherichia, Marko, Klebsiella, Mycobacterium, Leskur, Josipa, Dsaas, Modun, Dario, Vilovic, Elizabethkingia, Acinetobacter, Dinko, bruuniana, Maurizio, coli, baumannii, Soltanska, Ciani, Microorganisms, Seselja, Marino, Luterbach, Darko, =, Martinovic, Staphylococcus


Статья 5:
Имена и фамилии: Michael, Onyema, K, Devvret, Era, Khalid, Saudi, Prospects, Essinger, xi, King, Gregory, Graphic, Arabia, Elhaj, Rockson, Bayes, Deemed, =, Kwasi


Статья 6:
Имена и фамилии: Tt, Ju, minima, Δt, Ωi, Zhang, Machines, Pi, Metropolis, Wang, Xiangying, Lortaraprasert, Einstein, Waals, Zhao, Stern, Metasurface, Adversarial, Anuoluwa, Grid, Springer, Notably, Structure, Carlo, width, Xi, Xu, Shen, Reviews, Phonon, Wei, Pooling, Guo, Samuel, Algorithm, Research, Loss, |Ex, Wu, In, pj, B, Genetic, Bamidele, Mutation, Iterative, Emmanuel, Song, Carrete, Yang, Jin, Ji, Uncovering, Al(ν, Artificial, W., Narayana, atomistic, kijvij, Schematic, Gaussian, Element, height, Professor, Copyright, Selecting, Fourier, alumina, xspan, van, Heat, Kiarashinejad, ∇, Deformation, Seo, Fan, Al, De, Wan, Google, Graphene, Training, Laplacian, Fully, Hemmatyar, Fourth, Dr., Moreover, Indeed, Demonstrating, C., Fresnel, Accuracy, Psun, Yan, Wycoff, Alekseev, Variational, Ghiringhelli, Au, Herein, Dede, Chowdhury, Boltzmann, Cr, Guimei, Vector, Changliang, Zhu, Zhou, Autoencoder, Engineering, Dsi, Qpla, vice, Monte, vgτ, Ga, Weight, Liu, Sullivan, Jiang, Vi, Machine, Workflow, li, Si, Search, Pabs, Baowen, Forests, Raspberry, Pout, E., Peurifoy, Materials, R., et, Extending, Recent, Average, =, Objects, Particle, Foss, Hu, Li, Chen, max


Статья 7:
Имена и фамилии: Michael, S, Straight, Ratios, Emanuel, Schwarz, Campbell, Foundation, Junfang, Trakadis, Pharmaceuticals, Otsuka, P, Ratio, Pfizer, Michelle, Eric, vice, Pandey, Monte, al, Jiahui, Stephen, Jonathan, Barnett, Faraone, Yannis, Daniel, Jr., Fairlearn, e.g., Andreas, Multidisciplinary, Genomind, Yanli, Instability, Samples, Murray, M, Isabelle, Bichindaritz, J, Xiaoyu, Distill, Men, Carlo, Baer, Supplementary, Novartis, Hou, V, Thomas, Glatt, Cairns, =, Müller, Fuzzy, Chen


Статья 8:
Имена и фамилии: Pedregosa, Zhang, Khatibi, Peterson, Idoje, Olson, Kevin, Vincent, Uppu, Kondermann, Nejad, Morales, Twomey, Baxter, Polygons, James, Ray, Nets, Feng, Wei, and, Rød, Davis, Sen, Bill, Ahmed, Wu, Wen, Fu, Genetic, Graph, Maaten, Rosenblatt, Hara, Osman, Yu, Mazzia, Chang, Sampradeepraj, Tang, integer, Yang, Amir-, Neal, Ji, Artificial, Institute, Ali, Goodfellow, Moharram, Shin, Foundation, Abidi, Rice, values, Eelbode, Formal, Lai, Label, Gates, Ayesha, Mahmoud, Giovanny, Karimi, Dr., Abadi, Gano, Bah, Yan, Elbasi, Barvin, Hosseiniyan, Sarkar, Elavarasan, Guestrin, Zhu, Durrani, Jauhar, Greener, Killeen, Chebotarov, Dmytro, Liu, der, Jiang, Zou, Gao, Nar, Alzubaidi, Dege, Hamidi, Dahouda, Srinivas, Joe, Tune, Ghosh, Frank, et, =, Hu, Li, Chen, Su, Melinda


Статья 9:
Имена и фамилии: Intelligence, Markov, k-means, Jayatilake, Katubedda, Mudalige, C++, K-label, Regularization, emphysema, Phase, Chameleon, Sanger, Random, Don, Backpropagation, Moratuwa, Artificial, Sri, Gaussian, algorithm, =, Boltzmann, Cancer, Darwin


Статья 10:
Имена и фамилии: de, kernel, standard, Benchmark, Coulter, Franklin, Singer, Irvine, Zhang, Learn, ,, Roadwater, H., Kit, secondary, Overnight, Technologies, Miniprep, Carbonell, Analytik, S., Holowko, Bartosz, Jervis, Hercules, μL, Cytation, Bandit, Biotechnology, Hayman, C., Performance, Zumpe, Figure, E., Kernel, Beckman, Chao, B., et, Artificial, Supplementary, Mengyan, =, Cheng, Instruments, M., Brea